sudo: false

language: node_js
node_js:
  - 'stable'

cache:
  directories:
  - node_modules

script:
  - npm run build

branches:
  only:
    - master

deploy:
  provider: heroku
  api_key:
    secure: HEROKU_API_KEY
  app: pet-project-github
  on:
    repo: dmitrbrvsk/github-project