sudo: false

language: node_js
node_js:
  - 'stable'

cache:
  directories:
  - node_modules

script:
  - npm run build

branches:
  only:
    - master

deploy:
  provider: heroku
  api_key:
    secure: 'a78d7ee4-2690-43f8-a296-0749fd8c7212'
  app: pet-project-github
  on:
    repo: dmitrbrvsk/github-project