export const URL_API = 'https://api.github.com'

// REDUX STATES
export const SEARCH_ISSUES_REQUEST = 'SEARCH_ISSUES_REQUEST'
export const SEARCH_ISSUES_SUCCESS = 'SEARCH_ISSUES_SUCCESS'
export const SEARCH_ISSUES_FAILED = 'SEARCH_ISSUES_FAILED'

export const LOAD_ISSUE_REQUEST = 'LOAD_ISSUE_REQUEST'
export const LOAD_ISSUE_SUCCESS = 'LOAD_ISSUE_SUCCESS'
export const LOAD_ISSUE_FAILED = 'LOAD_ISSUE_FAILED'

export const SEARCH_REPOS_REQUEST = 'SEARCH_REPOS_REQUEST'
export const SEARCH_REPOS_SUCCESS = 'SEARCH_REPOS_SUCCESS'
export const SEARCH_REPOS_FAILED = 'SEARCH_REPOS_FAILED'

export const RESET = 'RESET'