export const URL_API = 'https://api.github.com'

// REDUX STATES
export const SEARCH_ISSUES_REQUEST = 'SEARCH_ISSUES_REQUEST'
export const SEARCH_ISSUES_SUCCESS = 'SEARCH_ISSUES_SUCCESS'
export const SEARCH_ISSUES_FAILED = 'SEARCH_ISSUES_FAILED' 